#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'steam_api'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'steam_api.cpp'
	]

	includes = []

	defines = []

	libs = []

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		idx      = bld.get_taskgen_count()
	)

