#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'inputsystem'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('NO_STRING_T',1)

def build(bld):
	source = [
		'inputstacksystem.cpp',
		'inputsystem.cpp',
		'joystick_linux.cpp',
		'steamcontroller.cpp',
		'key_translation.cpp',
		'../common/platforminputdevice.cpp',
		'../public/tier0/memoverride.cpp'
	]

	includes = [
		'.',
		'../public',
		'../public/tier0'
	]

	defines = []

	libs = ['tier0','tier1','tier2','vstdlib','interfaces','SDL2','steam_api']

	install_path = bld.env.LIBDIR

	bld.shlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		idx      = bld.get_taskgen_count()
	)

