#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'appframework'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'AppSystemGroup.cpp',
		'../public/filesystem_init.cpp',
		'posixapp.cpp',
		'sdlmgr.cpp'
	]

	includes = [
		'.',
		'../public',
		'../public/tier0',
		'../public/tier1'
	] + bld.env.INCLUDES_SDL2

	defines = []

	libs = []

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		idx      = bld.get_taskgen_count()
	)

