#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'lzma'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('_NO_EXCEPTIONS',1)
	conf.define('_LZMA_PROB32',1)
	conf.define('_7ZIP_ST',1)

def build(bld):
	source = [
		'lzma.cpp',
		'C/LzmaEnc.c',
		'C/LzmaDec.c',
		'C/LzFind.c'
	]

	includes = [
		'../../public',
		'C'
	]

	defines = []

	libs = []

	bld.stlib(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx',
		includes = includes,
		defines  = defines,
		use      = libs,
		idx      = bld.get_taskgen_count()
	)

