#! /usr/bin/env python
# encoding: utf-8

from __future__ import print_function
from waflib import Logs, Context, Configure
import sys
import os

VERSION = '1.35.8.0'
APPNAME = 'OpenCSGO'
top = '.'

FT2_CHECK='''extern "C" {
#include <ft2build.h>
#include FT_FREETYPE_H
}

int main() { return FT_Init_FreeType( NULL ); }
'''

FC_CHECK='''extern "C" {
#include <fontconfig/fontconfig.h>
}

int main() { return (int)FcInit(); }
'''

Context.Context.line_just = 55 # should fit for everything on 80x26

projects={
	'game': [
		'tier0',
		'tier1',
		'tier2',
		'tier3',
		'interfaces',
		'vstdlib',
		'mathlib',
		'mathlib/extended',
		'togl',
		'bitmap',
		'dmxloader',
		'vtf',
		'vpklib',
		'appframework',
		'bonesetup',
		'choreoobjects',
		'videocfg',
		'raytrace',
		'resourcefile',
		'particles',
		'soundsystem/lowlevel',
		'responserules/runtime',
		'vgui2/matsys_controls',
		'vgui2/vgui_controls',
		'launcher',
		'launcher_main',
		'vphysics',
		'filesystem',
		'inputsystem',
		'gameui',
		'gcsdk',
		'matchmaking',
		'game/client',
		'game/server',
		'engine',
        'materialsystem',
        'materialsystem/shaderapidx9',
        'materialsystem/shaderlib',
		'materialsystem/stdshaders',
		'thirdparty/quickhull',
		'thirdparty/protobuf-2.6.1',
		'thirdparty/crypto++-8.70',
		'thirdparty/libpng-1.6.39',
		'thirdparty/jpeg-9e',
		'thirdparty/zlib-1.2.13',
		'utils/lzma',
		'utils/bzip2',
		'ivp/havana',
		'ivp/havana/havok/hk_base',
		'ivp/havana/havok/hk_math',
		'ivp/ivp_compact_builder',
		'ivp/ivp_physics',
		'steamapi'
	],
	'dedicated': [
	]
}

@Configure.conf
def check_pkg(conf, package, uselib_store, fragment, *k, **kw):
	errormsg = '{0} not available! Install {0} development package. Also you may need to set PKG_CONFIG_PATH environment variable'.format(package)
	confmsg = 'Checking for \'{0}\' sanity'.format(package)
	errormsg2 = '{0} isn\'t installed correctly. Make sure you installed proper development package for target architecture'.format(package)

	try:
		conf.check_cfg(package=package, args='--cflags --libs', uselib_store=uselib_store, *k, **kw )
	except conf.errors.ConfigurationError:
		conf.fatal(errormsg)

	try:
		conf.check_cxx(fragment=fragment, use=uselib_store, msg=confmsg, *k, **kw)
	except conf.errors.ConfigurationError:
		conf.fatal(errormsg2)

@Configure.conf
def get_taskgen_count(self):
	try: idx = self.tg_idx_count
	except: idx = 0 # don't set tg_idx_count to not increase counter
	return idx

def define_platform(conf):
	conf.env.DEDICATED = conf.options.DEDICATED
	conf.env.GL = conf.options.GL

	if conf.options.DEDICATED:
		conf.options.SDL = False
		conf.define('DEDICATED', 1)

	if conf.options.GL:
		conf.env.append_unique('DEFINES', [
			'DX_TO_GL_ABSTRACTION',
			'GL_GLEXT_PROTOTYPES'
		])

	if conf.options.SDL:
		conf.define('USE_SDL', 1)

	if conf.options.ALLOW64:
		conf.define('PLATFORM_64BITS', 1)

	if conf.env.DEST_OS == 'linux':
		conf.define('_GLIBCXX_USE_CXX11_ABI',0)
		conf.env.append_unique('DEFINES', [
			'LINUX=1', '_LINUX=1',
			'POSIX=1', '_POSIX=1', 'PLATFORM_POSIX=1',
			'GNUC',
			'NO_VCR',
			'_DLL_EXT=.so'
		])

	if conf.env.DEST_OS == 'android':
		conf.define('_GLIBCXX_USE_CXX11_ABI',0)
		conf.env.append_unique('DEFINES', [
			'ANDROID=1', '_ANDROID=1',
			'LINUX=1', '_LINUX=1',
			'POSIX=1', '_POSIX=1',
			'GNUC',
			'NO_VCR',
			'_DLL_EXT=.so'
		])

	if conf.options.DEBUG_ENGINE:
		conf.env.append_unique('DEFINES', [
			'DEBUG', '_DEBUG'
		])
	else:
		conf.env.append_unique('DEFINES', [
			'NDEBUG'
		])

	conf.define('RAD_TELEMETRY_DISABLED',1)
	conf.define('CSTRIKE15',1)
	conf.define('CSTRIKE_REL_BUILD',1)
	conf.define('VERSION_SAFE_STEAM_API_INTERFACES',1)

def options(opt):
	grp = opt.add_option_group('Common options')

	grp.add_option('-8', '--64bits', action = 'store_true', dest = 'ALLOW64', default = False,
		help = 'allow targetting 64-bit engine [default: %default]')

	grp.add_option('-d', '--dedicated', action = 'store_true', dest = 'DEDICATED', default = False,
		help = 'build dedicated server [default: %default]')

	grp.add_option('-D', '--debug-engine', action = 'store_true', dest = 'DEBUG_ENGINE', default = False,
		help = 'build with -DDEBUG [default: %default]')

	grp.add_option('--use-sdl', action = 'store', dest = 'SDL', type = 'int', default = True,
		help = 'build engine with SDL [default: %default]')

	grp.add_option('--use-togl', action = 'store', dest = 'GL', type = 'int', default = True,
		help = 'build engine with ToGL [default: %default]')

	grp.add_option('--use-ccache', action = 'store_true', dest = 'CCACHE', default = False,
		help = 'build using ccache [default: %default]')

	grp.add_option('--disable-warns', action = 'store_true', dest = 'DISABLE_WARNS', default = False,
		help = 'disable compilation warnings [default: %default]')

	opt.load('compiler_optimizations subproject')

	opt.load('xcompile compiler_cxx compiler_c sdl2 clang_compilation_database strip_on_install waf_unit_test subproject')

	opt.load('reconfigure')

def configure(conf):
	conf.load('fwgslib reconfigure subproject xcompile compiler_c compiler_cxx gitversion clang_compilation_database strip_on_install waf_unit_test enforce_pic')
	define_platform(conf)

	if conf.env.DEST_OS == 'linux' and conf.env.DEST_CPU == 'x86_64':
		conf.env.BIT32_MANDATORY = not conf.options.ALLOW64
		if conf.env.BIT32_MANDATORY:
			Logs.info('WARNING: will build engine for 32-bit target')
	else:
		conf.env.BIT32_MANDATORY = False

	conf.load('force_32bit')

	if conf.options.DISABLE_WARNS:
		compiler_optional_flags = [
			'-w',
			'-fdiagnostics-color=always',
		]
	else:
		compiler_optional_flags = [
			'-Wall',
			'-fdiagnostics-color=always',
			'-Wcast-align',
			'-Wuninitialized',
			'-Winit-self',
			'-Wstrict-aliasing',
			'-Wno-reorder',
			'-Wno-unknown-pragmas',
			'-Wno-unused-function',
			'-Wno-unused-but-set-variable',
			'-Wno-unused-value',
			'-Wno-unused-variable',
			'-faligned-new',
		]

	cxx_compiler_optional_flags = [
		'-fomit-frame-pointer',
		'-Wno-narrowing'
	]

	c_compiler_optional_flags = [
		'-fnonconst-initializers' # owcc
	]

	cflags, linkflags = conf.get_optimization_flags()

	flags = ['-pipe', '-fPIC', '-L'+os.path.abspath('.')+'/lib/'+conf.env.DEST_OS+'/'+conf.env.DEST_CPU+'/']

	if conf.env.COMPILER_CC != 'msvc':
		flags += ['-pthread']

	if conf.env.DEST_OS == 'android':
		flags += [
			'-I'+os.path.abspath('.')+'/thirdparty/curl/include',
			'-I'+os.path.abspath('.')+'/thirdparty/SDL2/include',
			'-I'+os.path.abspath('.')+'/thirdparty/freetype/include',
			'-llog'
		]

	if conf.env.DEST_CPU in ['arm','aarch64']:
		flags += ['-fsigned-char']

		if conf.env.DEST_OS != 'android':
			flags += ['-march=native', '-mtune=native']
	else:
		flags += ['-march=native','-mtune=native','-mfpmath=sse']


	cflags += flags
	linkflags += flags

	# And here C++ flags starts to be treated separately
	cxxflags = list(cflags) + ['-std=c++17','-fpermissive']

	if conf.env.COMPILER_CC == 'clang':
		linkflags += ['-fuse-ld=lld']

	if conf.env.COMPILER_CC == 'gcc':
		conf.define('COMPILER_GCC', 1)

	conf.check_cc(cflags=cflags, linkflags=linkflags, msg='Checking for required C flags')
	conf.check_cxx(cxxflags=cxxflags, linkflags=linkflags, msg='Checking for required C++ flags')

	conf.env.append_unique('CFLAGS', cflags)
	conf.env.append_unique('CXXFLAGS', cxxflags)
	conf.env.append_unique('LINKFLAGS', linkflags)

	cxxflags += conf.filter_cxxflags(compiler_optional_flags + cxx_compiler_optional_flags, cflags)
	cflags += conf.filter_cflags(compiler_optional_flags + c_compiler_optional_flags, cflags)

	conf.env.append_unique('CFLAGS', cflags)
	conf.env.append_unique('CXXFLAGS', cxxflags)
	conf.env.append_unique('LINKFLAGS', linkflags)
	conf.env.append_unique('INCLUDES', [os.path.abspath('common/')])

	if conf.env.DEST_OS != 'android':
		if conf.options.SDL:
			conf.check_cfg(package='sdl2', uselib_store='SDL2', args=['--cflags', '--libs'])
		if conf.options.DEDICATED:
			conf.check_cfg(package='libedit', uselib_store='EDIT', args=['--cflags', '--libs'])
		else:
			conf.check_pkg('freetype2', 'FT2', FT2_CHECK)
			conf.check_pkg('fontconfig', 'FC', FC_CHECK)
			conf.check_cfg(package='libcurl', uselib_store='CURL', args=['--cflags', '--libs'])
	else:
		conf.check(lib='SDL2', uselib_store='SDL2')
		conf.check(lib='freetype2', uselib_store='FT2')
		conf.check(lib='curl', uselib_store='CURL')
		if conf.env.DEST_CPU != 'aarch64':
			conf.check(lib='unwind', uselib_store='UNWIND')
			conf.check(lib='crypto', uselib_store='CRYPTO')
			conf.check(lib='ssl', uselib_store='SSL')

		if not conf.env.LIB_M:
			conf.check_cc(lib='m')

	if conf.env.DEST_OS != 'android':
		conf.env.LIBDIR = conf.env.PREFIX+'/bin/'
		conf.env.BINDIR = conf.env.PREFIX
	else:
		conf.env.LIBDIR = conf.env.BINDIR = conf.env.PREFIX

	if conf.options.CCACHE:
		conf.env.CC.insert(0, 'ccache')
		conf.env.CXX.insert(0, 'ccache')
		print( conf.env )

	if conf.options.DEDICATED:
		conf.add_subproject(projects['dedicated'])
	else:
		conf.add_subproject(projects['game'])

def build(bld):
	os.environ["CCACHE_DIR"] = os.path.abspath('.ccache/'+bld.env.COMPILER_CC+'/'+bld.env.DEST_OS+'/'+bld.env.DEST_CPU)

	if bld.env.DEDICATED:
		bld.add_subproject(projects['dedicated'])
	else:
		bld.add_subproject(projects['game'])
